[package]
name = "codelldb"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"

[dependencies]
raw_debug_protocol = { package = "debug-protocol", path = "deps/debug-protocol" }
lldb = { path = "deps/lldb" }
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
failure = "0.1.5"
failure_derive = "0.1.5"
log = "0.4.6"
env_logger = "0.6.1"
tokio = "0.1.14"
futures = "0.1.20"
bytes = "0.4.11"
regex = "1.1.7"
superslice = "1.0.0"
lazy_static = "1.3.0"
clap = "2.33.0"
cpython = { version = "0.2.1", default-features = false }

[features]
default = ["python2"]
python2 = ["cpython/python27-sys"]
python3 = ["cpython/python3-sys"]

[lib]
crate-type = ["cdylib"]
